### ISSUE TITLE
Invitation to Explore Our Recently Published Project and Collaborate

### ISSUE THREAD

**Issue by lingyue404** [WeixiangYAN/ClinicalLab#1]
Excited to discover the amazing project developed by you. And welcome to visit our similar paper [https://arxiv.org/abs/2404.14777], which was published on April 23, 2024. We look forward to your suggestions and feedback. If you have any ideas and want to cooperate with us, you are welcome.

**Comment by WeixiangYAN** [comment]
Hi Ling,

Thank you for letting us know about this exciting work! Although your work is concurrent with that of ClinicalLab, we will add relevant discussions and cite it in future camera-ready version! 

Thank you! I am look forward to cooperate with you in the future!

Best,
Weixiang
