### ISSUE TITLE
Does the ClinicalBench dataset contains image or it just contains text?  

### ISSUE THREAD

**Issue by wangpengyu-debug** [WeixiangYAN/ClinicalLab#3]
I want to use this benchmark to test some models on medical imaging on end to end senario. Does the ClinicalBench dataset contains image or it just contains text?

**Comment by WeixiangYAN** [comment]
Hi Pengyu,

Thank you for your interest in and support of our work! **The ClinicalBench dataset contains only text.** I have sent the dataset and relevant materials to the email address you provided, so please check it.

As we mentioned in our paper, our focus is on evaluating LLMs and the agent systems they support. Introducing image data would require the involvement of vision-language models to recognize medical images, which goes against our goal of assessing language models. Therefore, **we have invested significant time and resources to have experts from various specialties use professional terminology to describe imaging results in detail, ensuring that the key information is clearly conveyed in each case**. Additionally, image data processing is considered a distinct field in academia, particularly in medical image analysis, with dedicated datasets and benchmarks that are usually featured in conferences such as CVPR and ECCV.

If you wish to test an end-to-end medical imaging model, we recommend checking datasets and benchmarks recently published at conferences like CVPR, ECCV, and MM to evaluate your model! 

Thank you! If you have any further questions, feel free to discuss them with us!
